name: Buid bot-farm


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # workflow_dispatch:
  #   branches: [develop]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11.0
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.0
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements_dev.txt ]; then pip install -r requirements_dev.txt; fi
    - name: Test with pytest
      run: |
        pytest tests/test_app.py
